# Generated by Django 6.0.1 on 2026-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stuID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
