# Generated by Django 6.0.1 on 2026-03-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menucatagory',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('dishname', models.CharField(max_length=70)),
                ('dishdescription', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dishimage', models.ImageField(upload_to='dishimages')),
                ('isavailable', models.BooleanField()),
            ],
        ),
    ]
