# Generated by Django 6.0.1 on 2026-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=70)),
                ('stumail', models.CharField(max_length=70)),
                ('stupass', models.CharField(max_length=70)),
            ],
        ),
    ]
