# Generated by Django 6.0.1 on 2026-02-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(default='Not Commented', max_length=50),
        ),
    ]
