# Generated by Django 6.0.1 on 2026-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_students_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='students',
            name='stuid',
        ),
        migrations.RemoveField(
            model_name='students',
            name='stumail',
        ),
        migrations.RemoveField(
            model_name='students',
            name='stuname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='stupass',
        ),
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
