# Generated by Django 6.0.3 on 2026-04-22 19:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('card', 'Card on Delivery'), ('transfer', 'Bank Transfer'), ('easypaisa', 'EasyPaisa')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appetizers',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='beverages',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='breakfast',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='brunch',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='burgers',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cocktails',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='desserts',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='glutenfree',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='kidsmenu',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sandwiches',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='seafood',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sides',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='soups',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='specials',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='steaks',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vegan',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vegetarian',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('dish_name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(blank=True)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
