# Generated by Django 6.0.1 on 2026-03-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imiuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
