# Generated by Django 6.0.1 on 2026-03-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imiuploader', '0002_image_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
    ]

print("Migration 0003_remove_image_post applied successfully.")