# Generated by Django 6.0.3 on 2026-06-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=100)),
                ('father_guardian_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('residential_address', models.TextField(max_length=300)),
                ('previous_school_name', models.CharField(max_length=150)),
                ('class_applied_for', models.CharField(choices=[('9', 'Class 9 (SSC-I)'), ('10', 'Class 10 (SSC-II)'), ('11', 'Class 11 (HSSC-I)'), ('12', 'Class 12 (HSSC-II)')], max_length=2)),
                ('previous_class_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cnic_bform_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('religion', models.CharField(choices=[('islam', 'Islam'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('sikhism', 'Sikhism'), ('other', 'Other')], max_length=20)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(upload_to='passports/')),
                ('declaration', models.BooleanField()),
                ('parent_signature', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
