# Generated by Django 6.0.3 on 2026-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='class_applied_for',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='cnic_bform_number',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='father_guardian_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='parent_occupation',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='parent_signature',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='previous_class_marks',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='previous_school_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_full_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
