# Generated by Django 6.0.1 on 2026-02-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=70)),
                ('courseFee', models.IntegerField()),
                ('seatsAvailable', models.IntegerField()),
                ('courseID', models.IntegerField()),
            ],
        ),
    ]
